### ISSUE TITLE
stroke.color does not work properly

### ISSUE THREAD

**Issue by maxmerben** [ropensci/lingtypology#87]
I have a dataset in the TALD format. I want the datapoint color to denote the value of the feature and the stroke color to denote the language. However, I have a lot of languages (> 10), and I want to specify colors so that they're not shades of gray. I made a vector with all the colors I need and put them into a separate column in the dataset according to the datapoint's language. Then I tried to create the map:

```
library(tidyverse)
library(lingtypology)

data <- read_delim("lezgic.csv", delim = "\t")
data <- data[(data$map == "yes"),]

system_colors = c("blue2", "red2", "gold2", "green3")

lang_colors = c(
  "Agul"="lightpink1",
  "Archi"="firebrick2",
  "Budukh"="olivedrab2",
  "Kryz"="limegreen",
  "Lezgian"="mediumorchid3",
  "Rutul"="deepskyblue",
  "Tabasaran"="indianred1",
  "Tsakhur"="dodgerblue3",
  "Udi"="orange2"
)

data$color = as.character(lang_colors[data$lang])

map.feature(
  languages = data$lang,
  label = data$lang,
  features = data$value,
  title = "Numeral systems",
  popup = data$idiom,
  latitude = data$latitude,
  longitude = data$longitude,
  color = system_colors,
  stroke.features = data$lang,
  stroke.color = unique(data$color),
  tile = "Stamen.TonerLite",
  width = 10
)
```
The map can be seen [here](https://sun9-east.userapi.com/sun9-33/s/v1/ig2/bFTTnL9YfPhlA6JIk8xFfvOvtMP5orq8nMlgwYqVavedSn3Yh_FfuLOKxg-0O2LZuNLSx_eX9A12bY-owJoL-X7g.jpg?size=831x483&quality=95&type=album). The stroke's colors do not match with the languages in the legend :( For some reason, they go backwards: orange, which was supposed to be Udi (the last language in the list), is the color of Agul (the first language in the list), etc. Meanwhile, `data$lang` and `data$color` are adequate:

```
> data$lang
 [1] "Archi"     "Agul"      "Agul"      "Agul"      "Agul"      "Agul"     
 [7] "Agul"      "Agul"      "Agul"      "Agul"      "Agul"      "Rutul"    
[13] "Rutul"     "Rutul"     "Rutul"     "Tabasaran" "Tabasaran" "Tabasaran"
[19] "Tsakhur"   "Tsakhur"   "Lezgian"   "Lezgian"   "Lezgian"   "Lezgian"  
[25] "Lezgian"   "Lezgian"   "Lezgian"   "Lezgian"   "Lezgian"   "Budukh"   
[31] "Kryz"      "Udi"       "Udi"      
> data$color
 [1] "firebrick2"    "lightpink1"    "lightpink1"    "lightpink1"   
 [5] "lightpink1"    "lightpink1"    "lightpink1"    "lightpink1"   
 [9] "lightpink1"    "lightpink1"    "lightpink1"    "deepskyblue"  
[13] "deepskyblue"   "deepskyblue"   "deepskyblue"   "indianred1"   
[17] "indianred1"    "indianred1"    "dodgerblue3"   "dodgerblue3"  
[21] "mediumorchid3" "mediumorchid3" "mediumorchid3" "mediumorchid3"
[25] "mediumorchid3" "mediumorchid3" "mediumorchid3" "mediumorchid3"
[29] "mediumorchid3" "olivedrab2"    "limegreen"     "orange2"      
[33] "orange2"      
```

I don't know if it's my mistake or something is wrong with the strokes in the library. If it is my mistake, maybe you could include an example of specifying the strokes' colors in [the guide](https://ropensci.github.io/lingtypology/lingtypology_creating_maps.html)?

<details> <summary> info about OS and package versions </summary>
```
> sessionInfo()$R.version$platform
[1] "x86_64-w64-mingw32"
> sessionInfo()$R.version$version.string
[1] "R version 4.1.1 (2021-08-10)"
> packageVersion("leaflet")
[1] ‘2.0.4.1’
> packageVersion("lingtypology")
[1] ‘1.1.10’
```
</details>

**Comment by agricolamz** [comment]
It is hard for me to reproduce without the example dataset. I expect that the color vector in the `stroke.color` argument should be given in the alphabetic order of corresponding languages.

**Comment by agricolamz** [comment]
@maxmerben?

**Comment by maxmerben** [comment]
sorry!
added the csv file [here](https://gist.github.com/maxmerben/6e9d560fdd917a137d4814ebd670640f) as you asked

**Comment by agricolamz** [comment]
This is a strange bug. First, you always can use `rev(unique(data$color))` in the `stroke.color` argument. However, I fixed this in the development version and soon it will be on CRAN.

**Comment by agricolamz** [comment]
However, you have some problems with the code too. Here is mine:

```
library(tidyverse)
library(lingtypology)

data <- read_csv("lezgic_numeral_systems.csv")
data <- data[(data$map == "yes"),]

system_colors = c("blue2", "red2", "gold2", "green3")

lang_colors = c(
  "Agul"="lightpink1",
  "Archi"="firebrick2",
  "Budukh"="olivedrab2",
  "Kryz"="limegreen",
  "Lezgian"="mediumorchid3",
  "Rutul"="deepskyblue",
  "Tabasaran"="indianred1",
  "Tsakhur"="dodgerblue3",
  "Udi"="orange2"
)

data |> 
  count(lang, color)

data$color = as.character(lang_colors[data$lang])

map.feature(
  languages = data$lang,
  label = data$lang,
  features = data$value,
  title = "Numeral systems",
  popup = data$idiom,
  latitude = data$latitude,
  longitude = data$longitude,
  color = system_colors,
  stroke.features = data$lang,
  stroke.color = lang_colors,
  tile = "Stamen.TonerLite",
  width = 10
)
```
![image](https://github.com/ropensci/lingtypology/assets/15956515/723b382e-df9c-44df-b534-5c1bf279c9c3)

**Comment by maxmerben** [comment]
Thank you very much! Still does not work but I'm looking forward to getting a fix patch :)
